//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pretorianie.Tytan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pretorianie.Tytan.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TytanNET - Project Reference.
        /// </summary>
        internal static string ActionDialogTitle_ReferenceProject {
            get {
                return ResourceManager.GetString("ActionDialogTitle_ReferenceProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear stored filter elements?.
        /// </summary>
        internal static string Question_DebugView_ClearFilter {
            get {
                return ResourceManager.GetString("Question_DebugView_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected project is already referenced..
        /// </summary>
        internal static string ReferenceProject_AlreadyReferenced {
            get {
                return ResourceManager.GetString("ReferenceProject_AlreadyReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected project is not valid..
        /// </summary>
        internal static string ReferenceProject_NotValidProject {
            get {
                return ResourceManager.GetString("ReferenceProject_NotValidProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output of {0}.
        /// </summary>
        internal static string ReferenceProject_OutputText {
            get {
                return ResourceManager.GetString("ReferenceProject_OutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add reference to project: {0}.
        /// </summary>
        internal static string ReferenceProject_ToolTip {
            get {
                return ResourceManager.GetString("ReferenceProject_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [not accessible].
        /// </summary>
        internal static string RegistryView_NotAccessible {
            get {
                return ResourceManager.GetString("RegistryView_NotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value named: &apos;{0}&apos; already exists. Do you want to replace it?.
        /// </summary>
        internal static string RegistryView_ReplaceConfirm {
            get {
                return ResourceManager.GetString("RegistryView_ReplaceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one option to search for..
        /// </summary>
        internal static string RegistryView_SelectOptionToSearch {
            get {
                return ResourceManager.GetString("RegistryView_SelectOptionToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new binary value.
        /// </summary>
        internal static string RegistryView_TitleAddBinary {
            get {
                return ResourceManager.GetString("RegistryView_TitleAddBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new registry key.
        /// </summary>
        internal static string RegistryView_TitleAddKey {
            get {
                return ResourceManager.GetString("RegistryView_TitleAddKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new string value.
        /// </summary>
        internal static string RegistryView_TitleAddString {
            get {
                return ResourceManager.GetString("RegistryView_TitleAddString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit value.
        /// </summary>
        internal static string RegistryView_TitleEdit {
            get {
                return ResourceManager.GetString("RegistryView_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change the name of that key..
        /// </summary>
        internal static string RegistryView_UnableToChangeName {
            get {
                return ResourceManager.GetString("RegistryView_UnableToChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug View.
        /// </summary>
        internal static string ToolWindowTitle_DebugView {
            get {
                return ResourceManager.GetString("ToolWindowTitle_DebugView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Vars.
        /// </summary>
        internal static string ToolWindowTitle_EnvironmentVars {
            get {
                return ResourceManager.GetString("ToolWindowTitle_EnvironmentVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Image Preview.
        /// </summary>
        internal static string ToolWindowTitle_NativeImagePreview {
            get {
                return ResourceManager.GetString("ToolWindowTitle_NativeImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry View.
        /// </summary>
        internal static string ToolWindowTitle_RegistryView {
            get {
                return ResourceManager.GetString("ToolWindowTitle_RegistryView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Finder.
        /// </summary>
        internal static string ToolWindowTitle_TypeFinder {
            get {
                return ResourceManager.GetString("ToolWindowTitle_TypeFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Reorder Refactor.
        /// </summary>
        internal static string UndoContext_AssignReorderRefactor {
            get {
                return ResourceManager.GetString("UndoContext_AssignReorderRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Property Refactor.
        /// </summary>
        internal static string UndoContext_ExtractPropertyRefactor {
            get {
                return ResourceManager.GetString("UndoContext_ExtractPropertyRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init Constructor Refactor.
        /// </summary>
        internal static string UndoContext_InitConstructorRefactor {
            get {
                return ResourceManager.GetString("UndoContext_InitConstructorRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Methods Refactor.
        /// </summary>
        internal static string UndoContext_MultiRenameRefactor {
            get {
                return ResourceManager.GetString("UndoContext_MultiRenameRefactor", resourceCulture);
            }
        }
    }
}
