//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pretorianie.Tytan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TipsTricks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipsTricks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pretorianie.Tytan.TipsTricks", typeof(TipsTricks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double-clicking on the text inside DebugView tool, will immediatelly jump to the source code, close to the line where the log entry was created..
        /// </summary>
        internal static string T0 {
            get {
                return ResourceManager.GetString("T0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebugView requires the log entries to have a special format to perform the jump quickly..
        /// </summary>
        internal static string T1 {
            get {
                return ResourceManager.GetString("T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebugView can at run-time filter incomming messages..
        /// </summary>
        internal static string T2 {
            get {
                return ResourceManager.GetString("T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are few log-entries formats automatically detected by DebugView tool..
        /// </summary>
        internal static string T3 {
            get {
                return ResourceManager.GetString("T3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to properties about given log entries of DebugView tool can be seen in Properties window, as long as given entry is selected..
        /// </summary>
        internal static string T4 {
            get {
                return ResourceManager.GetString("T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TytanNET is designed to support: C#, VB.NET and Managed C++..
        /// </summary>
        internal static string T5 {
            get {
                return ResourceManager.GetString("T5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to during debugging of your applications you can quickly preview some data by using visualizers:
        /// - XML documents,
        /// - images,
        /// - colors,
        /// - COM objects.
        /// </summary>
        internal static string T6 {
            get {
                return ResourceManager.GetString("T6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three tool windows are designed to enhance and speed-up your work:
        /// - DebugView - log capture and code navigation,
        /// - RegistryView - editor of system registry,
        /// - EnvironmentVariables - editor of environment variables.
        /// </summary>
        internal static string T7 {
            get {
                return ResourceManager.GetString("T7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Tips_First {
            get {
                return ResourceManager.GetString("Tips_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Tips_Last {
            get {
                return ResourceManager.GetString("Tips_Last", resourceCulture);
            }
        }
    }
}
