//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pretorianie.Tytan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TipsTricks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipsTricks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pretorianie.Tytan.TipsTricks", typeof(TipsTricks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double-clicking on the text inside DebugView tool, will immediately jump to the source code, close to the line where the log entry was created..
        /// </summary>
        internal static string T0 {
            get {
                return ResourceManager.GetString("T0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebugView requires the log entries to have a special format to perform the jump quickly..
        /// </summary>
        internal static string T1 {
            get {
                return ResourceManager.GetString("T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can quickly insert a Guid attribute to a class or just GUID string (depending on current cursor location) by clicking &apos;Insert Guid&apos; inside Refactor menu..
        /// </summary>
        internal static string T10 {
            get {
                return ResourceManager.GetString("T10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from DebugView you can quickly navigate to source-code by just double-clicking the log entry..
        /// </summary>
        internal static string T11 {
            get {
                return ResourceManager.GetString("T11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Editor can export data in the same format as a standard Windows&apos; registry editor (regedit.exe)..
        /// </summary>
        internal static string T12 {
            get {
                return ResourceManager.GetString("T12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Editor enhances the navigation over system registry..
        /// </summary>
        internal static string T13 {
            get {
                return ResourceManager.GetString("T13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by editing Environment Variables inside Visual Studio you don&apos;t need to restart it each time you want to change parameters for your tests..
        /// </summary>
        internal static string T14 {
            get {
                return ResourceManager.GetString("T14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can safe a lot of time just by using TytanNET coding enhancements and removing boring coding from your life!.
        /// </summary>
        internal static string T15 {
            get {
                return ResourceManager.GetString("T15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am always keen to listen your suggestions about TytanNET and how to improve it..
        /// </summary>
        internal static string T16 {
            get {
                return ResourceManager.GetString("T16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebugView can at run-time filter incoming messages..
        /// </summary>
        internal static string T2 {
            get {
                return ResourceManager.GetString("T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are few log-entries formats automatically detected by DebugView tool..
        /// </summary>
        internal static string T3 {
            get {
                return ResourceManager.GetString("T3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to properties about given log entries of DebugView tool can be seen in Properties window, as long as given entry is selected..
        /// </summary>
        internal static string T4 {
            get {
                return ResourceManager.GetString("T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TytanNET is designed to support: C#, VB.NET and Managed C++..
        /// </summary>
        internal static string T5 {
            get {
                return ResourceManager.GetString("T5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to during debugging of your applications you can quickly preview some data by using visualizers:
        /// - XML documents,
        /// - images,
        /// - colors,
        /// - COM objects.
        /// </summary>
        internal static string T6 {
            get {
                return ResourceManager.GetString("T6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three tool windows are designed to enhance and speed-up your work:
        /// - DebugView - log capture and code navigation,
        /// - RegistryView - editor of system registry,
        /// - EnvironmentVariables - editor of environment variables.
        /// </summary>
        internal static string T7 {
            get {
                return ResourceManager.GetString("T7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TytanNET allows insertion and edition of database connection strings using standard full-featured dialog box..
        /// </summary>
        internal static string T8 {
            get {
                return ResourceManager.GetString("T8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to edit connection string is enough to select a text in any text editor window and click &apos;Refactor-&gt;Quick Insert-&gt;Insert Connection String&apos;..
        /// </summary>
        internal static string T9 {
            get {
                return ResourceManager.GetString("T9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Tips_First {
            get {
                return ResourceManager.GetString("Tips_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string Tips_Last {
            get {
                return ResourceManager.GetString("Tips_Last", resourceCulture);
            }
        }
    }
}
